# Generated by Django 5.2.14 on 2026-05-10 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('duration', models.DurationField(verbose_name='Durata')),
                ('level', models.CharField(choices=[('BEGINNER', 'Principiante'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzato')], default='BEGINNER', max_length=20, verbose_name='Livello')),
                ('instructor_name', models.CharField(blank=True, max_length=200, verbose_name='Istruttore')),
                ('default_capacity', models.PositiveSmallIntegerField(default=10, verbose_name='Capienza default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='gyms.gym')),
            ],
            options={
                'verbose_name': 'Corso',
                'verbose_name_plural': 'Corsi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Inizio')),
                ('ends_at', models.DateTimeField(verbose_name='Fine')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, help_text='Vuoto = usa capienza default del corso', null=True, verbose_name='Capienza')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmata'), ('CANCELLED', 'Annullata'), ('COMPLETED', 'Completata')], default='SCHEDULED', max_length=20, verbose_name='Stato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='gyms.gym')),
            ],
            options={
                'verbose_name': 'Sessione',
                'verbose_name_plural': 'Sessioni',
                'ordering': ['starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='coursesession_ends_after_starts'), models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gt', 0), _connector='OR'), name='coursesession_capacity_positive_or_null')],
            },
        ),
    ]
