# Generated by Django 5.2.14 on 2026-05-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creata il')),
            ],
            options={
                'verbose_name': 'Palestra',
                'verbose_name_plural': 'Palestre',
                'ordering': ['name'],
            },
        ),
    ]
